Repository the-collab-lab/tcl-67-smart-shopping-list, pull requests merged in 2024-03, with the labels that each got.

#62 Issue 13 refinement
  src/components/ListItem.jsx
  src/utils/dates.js
  src/views/List.jsx
Labels: enhancement

#64 Rb ts improve list view 52
  src/App.jsx
  src/api/firebase.js
  src/components/AddItemForm.jsx
  src/components/ListItem.jsx
  src/components/ShareForm.jsx
  src/views/Layout.jsx
  src/views/List.css
  src/views/List.jsx
  src/views/ManageList.jsx
  src/views/index.js
  tests/components/List/List.test.jsx
  tests/components/ManageList/ManageList.test.jsx
Labels: bug fix, enhancement

#78 Copy updates on Shareform implemented
  src/components/ShareForm.css
  src/components/ShareForm.jsx
Labels: enhancement

#75 adds an item with new design criteria
  src/components/AddItemForm.jsx
  tests/components/AddItemForm/AddItemForm.test.jsx
Labels: enhancement

#77 Manage loading state for home and list views
  src/App.jsx
  src/api/firebase.js
  src/components/AddItemForm.jsx
  src/utils/dates.js
  src/views/Home.jsx
  src/views/List.jsx
  tests/components/AddItemForm/AddItemForm.test.jsx
  tests/components/List/List.test.jsx
Labels: bug fix

#81 homePage - No List Selected UI
  src/components/SelectListForm.jsx
  src/views/Home.jsx
Labels: bug fix

#88 List view restructure V.1
  src/components/AddItemForm.jsx
  src/components/ListItem.css
  src/components/ListItem.jsx
  src/components/ListSearchItems.jsx
  src/components/ShareForm.css
  src/components/ShareForm.jsx
  src/components/SingleList.css
  src/views/Layout.css
  src/views/List.css
  src/views/List.jsx
Labels: enhancement

#98 Add item section toggle 89
  src/components/AddItemForm.jsx
  src/views/List.css
Labels: enhancement
